FROM registry.cn-shanghai.aliyuncs.com/c7n/javabase:0.9.0
WORKDIR /choerodon
COPY app.jar agile-service.jar
COPY dist dist
COPY enterpoint.sh enterpoint.sh
RUN chmod 777 /choerodon/enterpoint.sh \
    && chown -R www-data:www-data /choerodon

CMD /choerodon/enterpoint.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /choerodon/agile-service.jar